Xp system
CircuitMess/Bit-Firmware pull request #28
Opened 2024-05-02 08:32 UTC by MiLeG

2024-05-03 08:06 UTC, Fr0zen3k commented on main/src/Games/Blocks/Blocks.cpp
> +	return linesCleared * 5;
Wtf sta nije ovo previse? Ja bez problema 400tinjak lineova clearam ak se potrudim...

2024-05-03 08:43 UTC, Fr0zen3k commented on main/src/Services/XPSystem.cpp
> +}
Nije mi bas jasno jesi li namijenio da leveli idu od 0-4 ili 1-5, jer ako idu od 0-4, MapXPToLevel ce ti vratiti na lvl 0 da ti je slijedeci level 2, a ako idu od 1-5, getLevel ce ti vratiti level 4 cak i ako si na level 5.

2024-05-03 08:47 UTC, Fr0zen3k requested changes
Mislim da bi trebalo smanjit tetris xp gain jer se moze odmah na lvl 3 prec ak se malo potrudis (potrudio sam se i dobio preko 800 score). Pogledaj comment sta sam napisao za xp system, bilo bi dobro i dodat komentar negdje za limite levela

2024-05-06 07:54 UTC, MiLeG commented on main/src/Games/Blocks/Blocks.cpp
> +	return linesCleared * 5;
Ma da ali zahtjeva puno vremena dok ti nagrindaš tolko linija pa sam mislio da je opravdano.
Budem stavio na *2

2024-05-06 08:27 UTC, MiLeG commented on main/src/Services/XPSystem.cpp
> +}
Leveli će biti od 1 do 5 jer će se tako prikazivati u UI-ju. LevelProgress će isto tako imati spremljen podatak.

2024-05-06 09:00 UTC, Fr0zen3k approved these changes

2024-05-06 09:00 UTC, merged